### ISSUE TITLE
QuickStart Tab

### ISSUE THREAD

**Issue by meaghanfitzgerald** [ava-labs/avalanche-docs#1382]
### Current Behavior

The documentation website currently includes a "QuickStart" tab that contains pages which are either obsolete or better suited to be placed in other tabs' subsections. This "QuickStart" tab is causing confusion for users and making the documentation structure less intuitive.

### Expected Behavior

We need to remove the "QuickStart" tab from the documentation website and reorganize the relevant pages to more appropriate sections. This will improve the user experience and ensure that the documentation is clear and easy to navigate.

### Steps to Reproduce

Visit the documentation website.
Observe the presence of the "QuickStart" tab.
Navigate through the "QuickStart" tab and notice the presence of obsolete or misplaced pages.

### Proposed Solution

Identify pages within the "QuickStart" tab that are obsolete and can be removed altogether, pages that are relevant but need improvement, or pages that are relevant with no edits needed. 

The current "QuickStart" tab is not serving its intended purpose and is creating confusion for users. Removing this tab and reorganizing the documentation pages will streamline the navigation and enhance the overall usability of the website.

**Comment by aaronbuchwald** [comment]
Thanks for re-organizing this. This isn't very QuickStart-esque atm.

Fuji Workflow - need to change the name, but how to use Fuji is worthwhile documentation for a QuickStart style page
Transfer AVAX Between Chains - useful for a QuickStart page since transfer between chains on the primary network is fundamental to using Avalanche
MultiSignature UTXOs with AvalancheJS - this is not really QuickStart
Avalanche Transaction Fee - this is basic reference material, not QuickStart
Adjusting Gas Price During High Network Activity - this is more dApps related and not QuickStart
Sending Transactions with Dynamic Fees - dApps not QuickStart
Tools and Utilities - this is more reference than QuickStart and is really just a list of repos
C-Chain Exchange Integration - not QuickStart, not sure where this should go, maybe Miscellaneous so we can link to it, but may not fit neatly under a top level header
Flow of a Single Blockchain - this is more reference material about the internals of AvalancheGo than QuickStart
