### ISSUE TITLE
Documentation on how to set up multiple nodes on the same machine

### ISSUE THREAD

**Issue by dubrado** [ava-labs/avalanche-docs#1421]
Would be nice to have a few tips on how to setup a 2nd node on a local machine for those building from their residential home, have seen this request a few times over the year.

**Comment by Mackenzie-OO7** [comment]
Hi @meaghanfitzgerald I would like to work on this issue.

**Comment by meaghanfitzgerald** [comment]
@Mackenzie-OO7 Any update?

**Comment by Mackenzie-OO7** [comment]
> @Mackenzie-OO7 Any update?

I had an issue with my machine earlier so I couldn't get started right away. Should be done with it today.

**Comment by meaghanfitzgerald** [comment]
@Mackenzie-OO7 We very much appreciate your effort to add to our developer documentation, however, our team has discussed and we will not be including this tutorial in our docs because we do not actually recommend that users run multiple nodes on the same machine. Doing so requires heavy oversight to ensure the resources required by each node do not conflict/overlap, and can have undesirable outcomes if not done properly. This tutorial also is not compliant with our [third-party docs policy](https://github.com/ava-labs/avalanche-docs/blob/master/policies/third-party-tooling-policy.md). Please feel free to reach out with any questions/concerns. We love open source contributions, so if you see any tickets open in the future please don't hesitate to raise a PR!
