### ISSUE TITLE
Node Version is Outdated in Using Hardhat with Avalanche C-Chain Guide

### ISSUE THREAD

**Issue by xanderdunn** [ava-labs/avalanche-docs#394]
The [Using Hardhat with Avalanche C-Chain Guide](https://docs.avax.network/build/tutorials/smart-contracts/using-hardhat-with-the-avalanche-c-chain) (new beta docks link [here](https://docs-beta.avax.network/build/tutorials/smart-contracts/using-hardhat-with-the-avalanche-c-chain/)) suggests using Node version 14.17.0, but this appears to be outdated:

```
$ npm install avalanche@latest
npm WARN notsup Unsupported engine for avalanche@3.9.3: wanted: {"node":">=16.13.0"} (current: {"node":"14.17.0","npm":"6.14.13"})
```

It's [here](https://github.com/ava-labs/avalanche-docs/blob/cc4b5e5116884da2fd4c67ecd9c9d9e9ac51383e/build/tutorials/smart-contracts/using-hardhat-with-the-avalanche-c-chain.md#nodejs-and-yarn) in this repo.

Current LTS appears to be Node 16.*

**Comment by cgcardona** [comment]
We removed the AvalancheJS dep on nodejs v >= 16.x due to the web wallet not building properly. AvalancheJS [now supports nodejs v >=14.0.0](https://github.com/ava-labs/avalanchejs/blob/master/package.json#L78-L80). However I'll update the docs to reflect that [the latest NodeJS v is 18.x](https://nodejs.org/en/)

**Comment by cgcardona** [comment]
This issue is resolved in this PR https://github.com/ava-labs/avalanche-docs/pull/1092
